### ISSUE TITLE
Question: What are the differences between this repo and react-native-create-library?

### ISSUE THREAD

**Issue by fdnhkj** [peggyrayzis/react-native-create-bridge#11]
Hi!

Thanks for your work, I'll have a look at it :)

I am currently using [react-native-create-library](https://github.com/frostney/react-native-create-library) and I was wondering what are the differences (if there are) between this repo and react-native-create-library.

**Comment by charliesbox** [comment]
I have the same question :)

**Comment by peggyrayzis** [comment]
Hi there! 🙋 `react-native-create-library` is an awesome project, but there are a couple key differences:
- `react-native-create-library` only supports library templates. `react-native-create-bridge` (RNCB) was originally intended to support bridges within an existing RN project, but it also supports library templates. Check out [the Shoutem team's post](https://medium.com/shoutem/top-lessons-we-learned-while-building-a-react-native-bridge-library-bd6485cc6212) on how they used RNCB to scaffold their Shopify library.
- RNCB also supports native UI components, whereas `react-native-create-library` does not. Within the next week, I plan on separating native UI components & native modules into their own separate templates since the majority of people creating a bridge are doing one or the other, not both.
- RNCB has Kotlin & Swift support
- `react-native-create-library` assumes that you're using Cocoapods to manage your iOS native dependencies. RNCB doesn't make this assumption, so you're free to use Carthage or Cocoapods.
- The templates generated by RNCB have comments with links to the docs to walk you through the bridging process. Some users might consider this an annoyance, so I eventually want to add support to remove the comments.
- `react-native-create-library` has RN for Windows support. I plan on adding this feature soon to RNCB!

Hope this helps!

**Comment by fdnhkj** [comment]
Ok I understand, thank you for taking the time 😊
