### ISSUE TITLE
Linking iOS

### ISSUE THREAD

**Issue by chrise86** [peggyrayzis/react-native-create-bridge#24]
In the readme you say:

> To complete the bridging process, look for AppDelegate.h in ios/yourapp
> Add #import <YourModule/YourModule.h> to the top of the file

When I do that, I get:

```
fatal error: 'RNTestModule/RNTestModule.h' file not found
```

The files live in the root of `ios/` folder - not in the project folder within, i.e. `ios/MyApp`. Could that be the reason?

**Comment by peggyrayzis** [comment]
Hi there! Thanks for using RNCB and reporting this bug.

That was actually an error in the readme from a previous iteration where I was considering adding Cocoapods support. I've removed it, you should be good to go 😀

**Comment by chrise86** [comment]
Ah ok!

I had to manually add the files to the project in Xcode for it to pick them up. Should this be necessary? 🤔

**Comment by peggyrayzis** [comment]
No, this shouldn't be necessary. Can you please provide more info about your setup? Are you in an existing RN project? If so, what's your version #?

**Comment by chrise86** [comment]
Yes existing project:

```
"react": "16.0.0-alpha.6",
"react-native": "0.44.0",
```

**Comment by peggyrayzis** [comment]
I was able to reproduce your issue last night creating a demo project. Originally, I thought you meant that you had to manually add React files like `RCTBridgeModule`.

You will have to manually add your files generated from RNCB because we don't currently edit your existing files like `project.pbxproj`. Thank you for catching this though because this was definitely an opportunity to improve the readme. 😀 

Also, I put bridge modules in the root of `ios/` because [folders can get weird in Xcode](http://www.thomashanning.com/xcode-groups-folder-references/) and everyone has their own preferences. I tend to use groups instead of folders on disk to organize my bridge modules, but that's up to you.
