### ISSUE TITLE
Understanding the plugin and where is .xcodeproj

### ISSUE THREAD

**Issue by RWOverdijk** [peggyrayzis/react-native-create-bridge#32]
The following question is probably pretty stupid, but I don't have the answer.

### Context

I'm creating a plugin for an sdk that's not that popular yet, so there's no plugin for RN. I'm attempting to be the one writing it.

### The short version

Where's `foo.xcodeproj` after running the `create-bridge` command?

### The longer version

How does this all work? It's cool that the bridge gets created for me, but I'd like to know how it works. Why it works. I get the bridging stuff itself, I just don't know how this is all organized. How do I create the foo.xcodeproj dir? How do I make `react-native link` work for my third party sdk? Where does the sdk come from? Should I include it in the repository?

I'm sorry for the chaotic way I'm asking my question. It's mainly because I'm not sure what I should be asking.

**Update:** What does this plugin add other than `react-native new-library --name foo`? That seems pretty inclusive and has the .xcodeproj dir

~~**Another update:** I tried that command, but I can't for the life of me get react native to pick it up for me. NativeModules stays an empty project. Do I have to link it somewhere?~~ I had to call `react-native link specific-module-name`

**Comment by Almouro** [comment]
@RWOverdijk I don't think the goal of `react-native-create-bridge` is to create a separate library. It creates the bridge inside an existing RN project, that's why it doesn't need an xcodeproj.

To get an actual separate library, [react-native-create-library](https://github.com/frostney/react-native-create-library) is probably what you're looking for.

@peggyrayzis is there a plan to ask the user if he wants to get a standalone library instead of a bridge in an existing app?

**Comment by RWOverdijk** [comment]
I've solved this using the react-native command that makes the plugin for me.
