### ISSUE TITLE
2.0.0 npm download missing src folder

### ISSUE THREAD

**Issue by cranberyxl** [peggyrayzis/react-native-create-bridge#44]
### Dev setup:
- `react-native-create-bridge` version: 2.0.0

### What you did:
`yarn add react-native-create-bridge`

### What happened:
```
$ ls node_modules/react-native-create-bridge/

.npmignore        LICENSE.md        README.md         node_modules/     templates/
CONTRIBUTING.md   MODULES.md        UI-COMPONENTS.md  package.json      yarn.lock
```
The `src` folder is missing from the npm download.

**Comment by jarretmoses** [comment]
@cranberyxl Sorry for the inconvenience. Will look to have this resolved ASAP.

**Comment by sullenor** [comment]
Hi, looks like a faced the similar issue :)
Just wanted to add that `package.json` `main` key points to `index.js` which is missing also.

**Comment by andrerfneves** [comment]
I'm able to reproduce the same error when trying to install it myself. Might have been because of #28. I can dig through this tomorrow at some point.

**Comment by jarretmoses** [comment]
@andrerfneves The problem I see is that the path to the index.js file doesn’t resolve from the build directory, because the build script isn’t run, which doesn’t have any changes from that PR. A fix is to just run the build script and having it sit on master but I never saw it on master in the first place. I’m looking to see if there is a missing post npm install script missing.

**Comment by jarretmoses** [comment]
`v2.0.1` has been published with a fix for this. The plugin should have actually been pointing to the `build`, thanks for pointing this out.

**Comment by cranberyxl** [comment]
Confirmed. Thanks!
